Using current date as default
rdzanyM/science_points pull request #75
Opened 2021-05-21 10:15 UTC by rdzanyM

2021-05-21 10:16 UTC, rdzanyM commented
![image](https://user-images.githubusercontent.com/43205483/119122064-67f05e00-ba2e-11eb-823d-3d30adcf260e.png)

2021-05-21 12:04 UTC, CrimsonRadiator requested changes
One thing I'd add is to change YYYY dates to YYYY-01-01 dates

2021-05-21 18:31 UTC, rdzanyM commented
![image](https://user-images.githubusercontent.com/43205483/119182600-68f7ae80-ba73-11eb-888d-01a9acf18ea7.png)

2021-05-22 08:45 UTC, CrimsonRadiator approved these changes

2021-05-22 08:45 UTC, merged